### ISSUE TITLE
Clarify DateTime.fromJSDate behavior

### ISSUE THREAD

**Issue by dstelljes** [icambron/luxon#36]
Currently, passing an invalid Date to DateTime.fromJSDate yields the current local DateTime:

```javascript
var DateTime = require("luxon").DateTime;

// works as described:
var a = new DateTime.fromJSDate(new Date(1000000000000));
a  // { [Number: 1000000000000] ... }
a.isValid  // true

// works, but isn't documented:
var b = new DateTime.fromJSDate(1000000000000);
b  // { [Number: 1000000000000] ... }
b.isValid  // true

// works, but unexpectedly:
var c = new DateTime.fromJSDate("totally not a date");
c  // { [Number: 1508613504066] ... }
c.isValid  // true
```

Intuitively, I'd expect an invalid JS Date to yield an invalid Luxon DateTime. What's the intended behavior?

**Comment by icambron** [comment]
Hmm, yeah. It currently does `new Date()` around the input, which has the effect of accepting anything the native date constructor accepts. I can't decide whether that's good and just needs documented or bad and needs removed.

**Comment by dstelljes** [comment]
Either way, it seemed weird that an invalid Date (`isNaN(new Date("garbage").getTime()) === true`) yields a valid DateTime. I'd be happy to work on a PR if you think the behavior should change.

**Comment by icambron** [comment]
I definitely agree with that. I think the fix for that goes [here](https://github.com/icambron/luxon/blob/master/src/datetime.js#L254); it ought to check if `ts` is NaN and if so set `invalidReason` to "invalid input". PR welcome.

**Comment by icambron** [comment]
Also I think I've decided to not accept alternative inputs for `fromJSDate`. So instead of `new Date(input).valueOf()` it should just say `input.valueOf ? input.valueOf() : NaN`. If people want to construct their own dates they can do that. (And if they provide something that has `valueOf` but isn't actually a Date, I suspect that's probably fine).

**Comment by dstelljes** [comment]
What would be the downside of just using `instanceof Date`? Fixed as described, `DateTime.fromJSDate("").isValid) === true`

**Comment by icambron** [comment]
This: https://github.com/moment/moment/issues/1084

**Comment by dstelljes** [comment]
Ah, gotcha. I guess I'd expect that the method would either (1) construct a Date with the input and use its `valueOf` or (2) take a hard line and do a more robust check. Based on what you said before, probably the latter.

**Comment by icambron** [comment]
I'm willing to adopt the `isDate` definition from that Moment issue
